# Generated by Django 4.1.3 on 2024-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('adm', 'Administrador'), ('tutor', 'Tutor'), ('student', 'Estudiante')], max_length=10)),
            ],
        ),
    ]
