# Generated by Django 4.1.3 on 2024-07-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_solapin'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
