# Generated by Django 4.2 on 2024-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_solapin'),
        ('users', '0004_userprofile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tutor_students',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='students.students'),
        ),
    ]
