# Generated by Django 4.1.3 on 2024-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rolesToCertify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('solapin', models.TextField()),
                ('faculty', models.CharField(choices=[('faculty1', 'Facultad 1'), ('faculty2', 'Facultad 2'), ('faculty3', 'Facultad 3'), ('faculty4', 'Facultad 4'), ('fte', 'FTE')], max_length=10)),
                ('center', models.TextField()),
                ('year', models.IntegerField()),
                ('group', models.IntegerField()),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('stage', models.TextField()),
                ('roles', models.ManyToManyField(related_name='students', to='rolesToCertify.roletocertify')),
            ],
        ),
    ]
