# Generated by Django 4.1.3 on 2024-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.CharField(choices=[('Facultad 1', 'Facultad 1'), ('Facultad 2', 'Facultad 2'), ('Facultad 3', 'Facultad 3'), ('Facultad 4', 'Facultad 4'), ('FTE', 'FTE')], max_length=10),
        ),
    ]
