# Generated by Django 4.1.3 on 2024-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='solapin',
            field=models.TextField(unique=True),
        ),
    ]
