# Generated by Django 4.1.3 on 2024-06-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.IntegerField()),
                ('mlc', models.IntegerField()),
                ('usd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputCurrency', models.FloatField()),
                ('outputCurrency', models.FloatField()),
                ('moneyEntryType', models.CharField(max_length=3)),
                ('moneyExitType', models.CharField(max_length=3)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('shop', 'Shop')], max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.wallet')),
            ],
        ),
    ]
