# Generated by Django 4.1.3 on 2024-07-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='students.students'),
        ),
        migrations.AddField(
            model_name='genericcompetencies',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_competencies', to='record.record'),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='record.record'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='record.record'),
        ),
    ]
