# Generated by Django 4.1.3 on 2024-07-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_solapin'),
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='record',
        ),
        migrations.RemoveField(
            model_name='evaluations',
            name='record',
        ),
        migrations.RemoveField(
            model_name='genericcompetencies',
            name='record',
        ),
        migrations.RemoveField(
            model_name='specificcompetencies',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specificcompetencies',
            name='record',
        ),
        migrations.RemoveField(
            model_name='task',
            name='record',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='students.students'),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students.students'),
        ),
        migrations.AddField(
            model_name='genericcompetencies',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_competencies', to='students.students'),
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.students'),
        ),
        migrations.AlterField(
            model_name='record',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='students.students'),
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.CharField(choices=[('not_developed', 'No desarrollada'), ('low_development', 'Bajo desarrollo'), ('medium_development', 'Desarrollo medio'), ('developed', 'Desarrollada')], max_length=18)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency', to='students.students')),
            ],
        ),
        migrations.AddField(
            model_name='specificcompetencies',
            name='competency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_competencies', to='record.competency'),
        ),
    ]
