# Generated by Django 4.1.3 on 2024-07-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolesToCertify', '0001_initial'),
        ('record', '0005_rename_startgdate_task_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='genericcompetencies',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_competency_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='record',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='specificcompetencies',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_competency_roles', to='rolesToCertify.roletocertify'),
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to='rolesToCertify.roletocertify'),
        ),
    ]
