# Generated by Django 4.1.3 on 2024-08-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_competency_level_alter_evaluations_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluations',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
