# Generated by Django 4.1.3 on 2024-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_evaluations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='isPerformedRole',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='isPreferRole',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
